### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by BurningWitness**
As this is a complete rewrite of the library, it is completely incompatible with the previous version structure. A loose migration guide is part of the changelog. Cloning this fork and reading through the Haddock page might help, I've documented it rather succinctly.

The changes go as follows:

- `MBB` is now `MBR r`. `RTree` therefore obtains said `r` as a type argument in the first position.

  As GHC does not support polymorphic unboxing, the coordinates inside `MBR` are no longer unpacked. I have attempted to sidestep this issue via:
    - the use of the `primitive` library and the `PatternSynonyms` extension;
    - unboxed `MBR`s via a type family, generalized back to a single constructor via `PatternSynonyms`;
  
  Both cases resulted in spectacular failure with 3x slowdowns on insertions and deletions over the current version (no major slowdowns occurred in lookups, curiously enough). This leads me to believe the issue is with `PatternSynonyms` unpacking all four values back and forth on insertions and deletions, but I don't think optimizing this justifies any potential speed gains.

  In terms of usability, I think boxed coordinates are superior to unboxed `Double`s, as if you're using the library over integers or `Float`s, you have to pay the price of converting to and from `Double`, at best completely nullifying the unboxing gains.

- `RTree` was restructured to use `NonEmpty` and to operate in a generic fashion over any sane constants. Constants reside within `Data.RTree.Internal.Constants` and thus may be changed via mixins (if that ever becomes useful);

- Instead of baking predicates into functions, they've been generalized into a `Predicate` datatype. Additionally a slew of "strict" predicates have been added to exclude boxes merely touching;

- Lookup functions are not implented directly. Instead variations of `Foldable` functions are provided, allowing full control over
  the accumulator types. Therefore `lookup`/`intersects`/`cointain`/`within` can be used to look up whatever exactly needed. `map`/`traverse` alternatives are provided too;

- Bounding rectangle duplication is now explicitly permitted within the library. This was never a guarantee of the data structure in the first place, as insertions always traverse strictly one branch and therefore two insertions of the same value may well lead to two different underlying nodes. `delete` thus only ever removes the first occurrence of a bounding rectangle, as this is the most consistent definition for this function.

- Union functions, as well as `Semigroup` and `Monoid` instances relying on them have been removed. As `MBR`s are two-dimensional, there is no clear ordering that can be applied to them (no sensible `Ord` instance) and thus unions are highly inefficient. Obviously even a tremendously slow `Semigroup` instance would still be a valid one, but in my view, anyone using it would be using the library incorrectly;

- The `binary` dependency and the matching instances were removed. This is a rather complex topic:
  - `RTree` is not a list, nor does it convert to a list in `O (1)`. Transmitting it thus means moving every single node bounding rectangle, which incurs an `(M / M - 1) - 1` bounding rectangle overhead within the format (~33% within the default constants);
  - There are bulking algorithms, of which I've implemented `bulkSTR`, which give solid performance on both unpacking and lookups.
  
  The actual need for a `Binary` instance may thus only extend to applications that need to load a pre-baked `RTree` as fast as possible, which I do not think are common.
  
- `Generic` instances have been removed. I do not know if there is any use for them;

- Strictness guarantees have been relaxed to match those of other dictionary packages. The underlying datatype is also shared between both interfaces the same way.

Things that are arguably missing:

- `touches` predicate. The definition for it can be seen [on this webpage](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_Transformers/Transformers/spatialrelations.htm). Not implemented because of how little use it serves and because I don't have a clear algorithm.

Benchmarks:

Defined as the `time` benchmark, running over the exact same sequence of values every time.
  `0.6.0` benchmark code can be found at BurningWitness/r-tree@98d6e27.

<table>
  <thead>
    <tr>
      <th>Function</th>
      <th>Predicate</th>
      <th>Monoid</th>
      <th>Algorithm</th>
      <th>1.0.0 (-O1)</th>
      <th>1.0.0 (-O2)</th>
      <th>0.6.0 (-O1)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="3">insert</td>
      <td rowspan="3" colspan="2"></td>
      <td>BKSS</td>
      <td>77.58 ms</td>
      <td>75.64 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>57.43 ms</td>
      <td>56.68 ms</td>
      <td>23.66 ms</td>
    </tr>
    <tr>
      <td>STR</td>
      <td>8.411 ms</td>
      <td>8.791 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>delete</td>
      <td colspan="3"></td>
      <td>35.87 ms</td>
      <td>35.84 ms</td>
      <td>22.12 ms</td>
    </tr>
    <tr>
      <td rowspan="24">lookup</td>
      <td rowspan="6">equals</td>
      <td rowspan="3">First</td>
      <td>BKSS</td>
      <td>636.0 μs</td>
      <td>639.3 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>741.4 μs</td>
      <td>741.3 μs</td>
      <td>461.0 μs</td>
    </tr>
    <tr>
      <td>STR</td>
      <td>675.4 μs</td>
      <td>680.5 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">List</td>
      <td>BKSS</td>
      <td>1.279 ms</td>
      <td>1.290 m</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.643 ms</td>
      <td>1.632 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.541 ms</td>
      <td>1.533 ms</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="6">intersects</td>
      <td rowspan="3">First</td>
      <td>BKSS</td>
      <td>683.0 μs</td>
      <td>694.4 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>788.1 μs</td>
      <td>796.9 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>726.4 μs</td>
      <td>730.2 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">List</td>
      <td>BKSS</td>
      <td>1.337 ms</td>
      <td>1.318 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.716 ms</td>
      <td>1.698 ms</td>
      <td>1.950 ms</td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.593 ms</td>
      <td>1.607 ms</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="6">contains</td>
      <td rowspan="3">First</td>
      <td>BKSS</td>
      <td>658.6 μs</td>
      <td>689.8 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>772.0 μs</td>
      <td>772.1 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>705.5 μs</td>
      <td>706.3 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">List</td>
      <td>BKSS</td>
      <td>1.314 ms</td>
      <td>1.308 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.690 ms</td>
      <td>1.683 ms</td>
      <td>1.951 ms</td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.587 ms</td>
      <td>1.583 ms</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="6">within</td>
      <td rowspan="3">First</td>
      <td>BKSS</td>
      <td>683.4 μs</td>
      <td>689.8 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>785.4 μs</td>
      <td>804.4 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>713.5 μs</td>
      <td>722.2 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">List</td>
      <td>BKSS</td>
      <td>1.363 ms</td>
      <td>1.321 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.729 ms</td>
      <td>1.695 ms</td>
      <td>1.304 ms</td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.621 ms</td>
      <td>1.594 ms</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="12">map</td>
      <td rowspan="3">equals</td>
      <td rowspan="24"></td>
      <td>BKSS</td>
      <td>68.24 μs</td>
      <td>61.51 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>69.46 μs</td>
      <td>66.73 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>66.58 μs</td>
      <td>62.08 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">intersects</td>
      <td>BKSS</td>
      <td>64.10 μs</td>
      <td>63.42 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>65.17 μs</td>
      <td>72.03 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>67.11 μs</td>
      <td>63.82 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">contains</td>
      <td>BKSS</td>
      <td>61.89 μs</td>
      <td>63.23 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>70.93 μs</td>
      <td>80.32 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>62.27 μs</td>
      <td>64.50 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">within</td>
      <td>BKSS</td>
      <td>63.13 μs</td>
      <td>62.51 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>61.76 μs</td>
      <td>74.24 μs</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>69.70 μs</td>
      <td>62.14 μs</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="12">traverse</td>
      <td rowspan="3">equals</td>
      <td>BKSS</td>
      <td>1.093 ms</td>
      <td>1.083 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.595 ms</td>
      <td>1.611 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.530 ms</td>
      <td>1.532 ms</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">intersects</td>
      <td>BKSS</td>
      <td>1.133 ms</td>
      <td>1.128 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.650 ms</td>
      <td>1.651 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.605 ms</td>
      <td>1.595 ms</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">contains</td>
      <td>BKSS</td>
      <td>1.120 ms</td>
      <td>1.116 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.633 ms</td>
      <td>1.612 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.587 ms</td>
      <td>1.567 ms</td>
      <td></td>
    </tr>
    <tr>
      <td rowspan="3">within</td>
      <td>BKSS</td>
      <td>1.122 ms</td>
      <td>1.102 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>Gut</td>
      <td>1.622 ms</td>
      <td>1.611 ms</td>
      <td></td>
    </tr>
    <tr>
      <td>STR</td>
      <td>1.568 ms</td>
      <td>1.568 ms</td>
      <td></td>
    </tr>
  </tbody>
</table>

I attribute the performance loss on insertions and deletions to the lack of unboxing, which I don't consider an issue as the code is already fast enough.

The `-O2` flag doesn't bring any consistent improvements, so it's not enabled in the package.

Extras:

- I cobbled up an incredibly basic OpenGL-based visualizer for the trees. Doesn't serve any real purpose and is thus marked not buildable by default;
- Property tests were performed by comparing different sizes against applying the same operation to a dumb list. This is obviously not an exhaustive check, but it should suffice.
- I have no idea how to tests predicates. They're pretty much one-liners, but, as with `touches`, I do not have proper mathematical definitions on hand.

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
OH WOW!!!

**Comment by sebastian-philipp** [comment]
@BurningWitness would you be open for a chat about your work? I mean, this is well beyond a regular PR and I actually like to get in touch with you. Feel free to send a mail to sebastian@spawnhost.de.

**Comment by BurningWitness** [comment]
Spent a day rewriting this PR to use `SmallArray`s from `primitive` and curiously enough the results are about the same as with unboxed ones: about the same times for insertions, slight losses on deletions, 1.5x - 2x losses on lookups across the board and frankly insane losses for maps and traversals as avoiding reallocations slows the algorithm down to ~150ms per pass on my machine (the losses from doing it the dumb way are probably far smaller, but that requires reallocating the entire tree every time).

It did however help with resident memory usage quite a bit, slicing it by more than a half in case of BKSS.

To me this is a peculiar result as I expected boxed arrays to outperform single-linked lists through proper indexing, obviously, so at this point my theory is that GHC's optimizations for array management are lacking. I'm not going to investigate this any deeper as I'd need to get into the weeds that is the GHC compiler and even me figuring out the precise correct solution would still tie the code to the compiler far more than the current version.

**Comment by BurningWitness** [comment]
Superceded by #30.

**Pull request closed without merging**
