### PR TITLE
Fix to work from ghc-8.2.2 up to ghc-8.8.1

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Wow!

**Comment by sebastian-philipp** [comment]
I meant, you're using this? That's totally awesome.

**Comment by newhoggy** [comment]
Yep! 😁

**Comment by newhoggy** [comment]
Any chance to merge and publish new version?

**Comment by sebastian-philipp** [comment]
> Any chance to merge and publish new version?

yes! I just need to find the time to look into ghc 8.8.1. Maybe today, maybe this weekend, but definitively before December 19th.

**Comment by sebastian-philipp** [comment]
fyi, this is now pushed to https://hackage.haskell.org/package/data-r-tree-0.6.0

**Pull request merged**
